### PR TITLE
Update MythicDungeonTools.lua

### PR DESCRIPTION
**Pull request by nanjuekaien1**
Is it possible to add localization in these places?

### CODE REVIEW

**Comment by nanjuekaien1** [comment]
zhCN.lua

L["> More Dungeons"] = "> 更多地下城"
L["Legion"] = "军团来临"
L["BFA"] = "德拉诺"
L["Shadowlands"] = "暗影国度"
L["Shadowlands Season 4"] = "暗影国度-四赛季"

L["Default"] = "默认"
L["<New Preset>"] = "<新的方案>"
L["Empty"] = "空"

**Comment by Nnoggie** [comment]
approved and zhCN localizations added 👍will be available in next release v3.9.4.3

**Comment by nanjuekaien1** [comment]
Curseforge downloaded v3.9.4.3 found, zhCN you missed
"<New Preset>" = "<新的方案>"

**Comment by nanjuekaien1** [comment]
Since I can't register an account with curseforge, please help add the localization of zhCN.
Some I haven't found out yet, so I'll make it up.
thanks

L["Advisor Melandrus"] = "顾问麦兰杜斯"
L["Aggravated Skitterfly"] = "被激怒的掠蜓" 
L["Algeth'ar Educator"] = "艾杰斯亚教育者" 
L["Algeth'ar Enforcer"] = "艾杰斯亚执行者" 
L["Algeth'ar Nurse"] = "艾杰斯亚护士" 
L["Algeth'ar Security"] = "艾杰斯亚保安" 
L["AlgetharAcademy"] = "艾杰斯亚学院" 
L["Alpha Eagle"] = "头领鹰隼" 
L["AltarOfShadow"] = "暗影祭坛" 
L["Arcane Construct"] = "奥术构造体" 
L["Arcane Elemental"] = "奥术元素" 
L["Arcane Forager"] = "奥术抢劫者" 
L["Arcane Manifestation"] = "奥术化身"
L["Arcane Ravager"] = "奥术抢劫者" 
L["Arcane Tender"] = "奥术看护者"
L["Astral Attendant"] = "奥术侍从" 
L["Azureblade"] = "青刃"
L["Baalgar the Watchful"] = "警惕的巴尔戈"
L["Balakar Khan"] = "巴拉卡可汗"
L["Balara"] = "巴拉拉"
L["Batak"] = "巴塔克"
L["Blazebound Destroyer"] = "炎缚毁灭者" 
L["Blazing Imp"] = "炽燃小鬼"
L["Bonemaw"] = "骨喉"
L["Bound Energy"] = "被束缚的能量"
L["BrackenhideHollow"] = "蕨皮山谷"
L["Carrion Worm"] = "食腐蛆虫"
L["ChamberOfFlames"] = "烈焰密室" 
L["Conjured Lasher"] = "召唤的鞭笞者" 
L["Corpse Skitterling"] = "骸骨幼蛛"
L["Corrupted Manafiend"] = "被腐化的嗜魔者" 
L["Crawth"] = "克罗兹" 
L["CryptOfTheAncients"] = "先祖墓穴" 
L["Crystal Fury"] = "水晶之怒" 
L["Crystal Thrasher"] = "水晶构造体" 
L["CrystalChamber"] = "水晶密室" 
L["Defier Draghar"] = "亵渎者德拉加尔" 
L["Defiled Spirit"] = "被亵渎的幽灵"
L["DenOfDecay"] = "腐朽之穴" 
L["Desecrated Bakar"] = "被亵渎的獒犬"
L["Desecrated Ohuna"] = "被亵渎的欧胡纳"
L["Dragonflight Season 1"] = "巨龙时代第一赛季" 
L["Dragonflight Season 2"] = "巨龙时代第二赛季" 
L["Drakonid Breaker"] = "龙人破坏者" 
L["Duskwatch Arcanist"] = "暮色卫队奥术师"
L["Duskwatch Guard"] = "暮色卫队卫兵"
L["Duskwatch Sentry"] = "暮色卫队哨兵"
L["Echo of Doragosa"] = "多拉苟萨的回响" 
L["EdgeOfReality"] = "现世边界" 
L["Erkhart Stormvein"] = "厄克哈特·风脉" 
L["Felbound Enforcer"] = "邪缚执行者"
L["Flame Channeler"] = "烈焰引导者" 
L["Flamegullet"] = "烈焰之咽" 
L["Flashfrost Chillweaver"] = "闪霜织寒者" 
L["Flashfrost Earthshaper"] = "闪霜塑地者" 
L["Gerenth the Vile"] = "可疑的贵族"
L["Granyth"] = "格拉尼斯"
L["Guardian Construct"] = "构造体卫兵"
L["Guardian Sentry"] = "守护者哨兵" 
L["HallOfTheKeepers"] = "守护者大厅" 
L["HallsOfInfusion"] = "注能大厅" 
L["High Channeler Ryvati"] = "大引导者莱瓦迪" 
L["Hungry Lasher"] = "饥饿的鞭笞者" 
L["Imacu'tya"] = "伊玛库塔"
L["Infused Whelp"] = "注能龙崽" 
L["InfusersRotunda"] = "注能者圆厅"
L["Infusion Chambers"] = "注能室"
L["InfusionChamber"] = "注能室"
L["Jazshariu"] = "加兹沙尤"
L["Kokia Blazehoof"] = "柯姬雅·焰蹄" 
L["Kyrakka"] = "基拉卡"
L["Legion Hound"] = "军团猎犬"
L["Leymor"] = "莱魔" 
L["LowerChamber"] = "下层密室" 
L["Mana Saber"] = "魔刃豹"
L["Mana Wyrm"] = "法力浮龙"
L["Maruuk"] = "马鲁克"
L["MausoleumOfLegends"] = "传奇陵墓" 
L["Melidrussa Chillworn"] = "梅莉杜莎·寒妆" 
L["Monstrous Corpse Spider"] = "畸形僵尸蛛"
L["Neltharus"] = "奈萨鲁斯" 
L["Ner'zhul"] = "耐奥祖"
L["Nhallish"] = "纳利什"
L["Nokhud Beastmaster"] = "诺库德兽王"
L["Nokhud Hornsounder"] = "诺库德号角手"
L["Nokhud Longbow"] = "诺库德长弓手"
L["Nokhud Neophyte"] = "诺库顿新兵"
L["Nokhud Plainstomper"] = "诺库德平原践踏着"
L["Nokhud Warspear"] = "诺库德战矛"
L["Nullmagic Hornswog"] = "空魔龙蛙" 
L["Overgrown Ancient"] = "茂林古树" 
L["Patrol Captain Gerdo"] = "巡逻队长加多"
L["Plagued Bat"] = "疫病蝙蝠"
L["Primal Gust"] = "原始阵风"
L["Primal Juggernaut"] = "原始主宰" 
L["Primal Stormshield"] = "原始暴风之盾"
L["Primal Terrasentry"] = "原始土地哨卫" 
L["Primal Thundercloud"] = "原始雷云" 
L["Primalist Arcblade"] = "拜荒弧光之刃"
L["Primalist Cinderweaver"] = "拜荒织烬者"
L["Primalist Flamedancer"] = "拜荒烈焰舞者" 
L["Primalist Shockcaster"] = "拜荒者雷震法师" 
L["Primalist Stormspeaker"] = "拜荒雷语者"
L["Primalist Thunderbeast"] = "拜荒雷兽"
L["Reanimated Ritual Bones"] = "复苏的祭祀之骨"
L["Risen Mystic"] = "复活的秘术师"
L["Risen Warrior"] = "复活的战士"
L["Ruby Overlook"] = "红玉瞭望台" 
L["RubyLifePools"] = "红玉新生法池"
L["Rune Seal Keeper"] = "符文封印守护者" 
L["Sadana Bloodfury"] = "莎达娜·血怒"
L["Scalebane Lieutenant"] = "鳞灾副官" 
L["Scorchling"] = "灼烧元素" 
L["Shadow Mistress"] = "暗影女妖"
L["Shadowmoon Bone-Mender"] = "影月塑骨者"
L["Shadowmoon Enslaver"] = "影月奴役者"
L["Shadowmoon Exhumer"] = "影月盗墓者"
L["Shadowmoon Loyalist"] = "影月死忠者"
L["ShadowmoonBurialGrounds"] = "影月墓地" 
L["Shrieking Whelp"] = "尖叫的雏龙" 
L["Soulharvester Duuren"] = "灵魂收割者杜乌伦"
L["Soulharvester Galtmaa"] = "灵魂收割者加尔特玛"
L["Soulharvester Mandakh"] = "灵魂收割者马达克"
L["Soulharvester Tumen"] = "灵魂收割者图曼"
L["Spellbound Battleaxe"] = "缚法战斧" 
L["Spellbound Scepter"] = "缚法节杖" 
L["Storm Warrior"] = "风暴战士"
L["Stormcaller Arynga"] = "唤雷者阿琳佳"
L["Stormcaller Boroo"] = "唤雷者博鲁"
L["Stormcaller Solongo"] = "唤雷者索隆葛"
L["Stormcaller Zarii"] = "唤雷者扎莉伊"
L["Stormsurge Totem"] = "风暴激流图腾"
L["Subjugated Soul"] = "被奴役的亡魂"
L["Talixae Flamewreath"] = "塔丽克萨·火冠"
L["Tarasek Delver"] = "塔拉赛钻研者" 
L["Teera"] = "提拉"
L["Telash Greywing"] = "泰拉什·灰翼" 
L["Tempest Channeler"] = "暴风引导者" 
L["TempleOfTheJadeSerpent"] = "青龙寺"
L["Territorial Eagle"] = "领地鹰隼" 
L["The Raging Tempest"] = "狂怒风暴"
L["TheArcaneConservatory"] = "奥术植物园" 
L["TheAzureVault"] = "碧蓝魔馆" 
L["TheBurningCauldron"] = "燃烧坩埚" 
L["TheHeadteachersEnclave"] = "" 
L["TheNokhudOffensive"] = "诺库德阻击战" 
L["ThePitch"] = "体育场" 
L["TheScrollkeepersSanctum"] = "藏卷人密室" 
L["TheVaultOfTyr"] = "提尔宝库"
L["Thunderhead"] = "电角蜥蜴" 
L["Ukhel Beastcaller"] = "尤克赫尔驭兽师"
L["Ukhel Corruptor"] = "尤克赫尔腐蚀者"
L["Ukhel Deathspeaker"] = "尤克赫尔亡语者"
L["Ukhel Willcrusher"] = "尤克赫尔意志粉碎者"
L["UldamanLegacyOfTyr"] = "奥达曼：提尔的遗产" 
L["Umbrelskul"] = "安布雷斯库" 
L["Unruly Textbook"] = "任性的教科书" 
L["Unstable Curator"] = "奥术管理员" 
L["Unstable Squall"] = "不稳定的狂风"
L["UpperChamber"] = "上层密室" 
L["Vault Guard"] = "魔馆守卫" 
L["Vexamus"] = "维克萨姆斯" 
L["Vile Lasher"] = "恶毒的鞭笞者" 
L["Void Spawn"] = "虚空爪牙"
L["Volatile Sapling"] = "不稳定的树液" 
L["War Ohuna"] = "战鹰"
L["Watchful Inquisitor"] = "警觉的审判者"
L["openSettingsTooltip"] = "点击打开设置"

**Pull request merged**
